# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_article.ipynb.

# %% auto #0
__all__ = ['insert_article', 'get_article_by_id', 'get_article_by_path', 'get_articles_by_website', 'update_article_keyword',
           'delete_article', 'update_article_optimization']

# %% ../nbs/03_article.ipynb #fa7b3269
from sqlmodel import SQLModel, Field, create_engine, Session, select, Column
from sqlalchemy import JSON
from pydantic import field_validator
from datetime import datetime, date
from pathlib import Path


# %% ../nbs/03_article.ipynb #51f1f26c
class Article(SQLModel, table=True):
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    website_id: int = Field(foreign_key="website.id")
    file_path: str  # Path to .md file
    focus_keyword: str | None = None
    secondary_keywords: list[str] | None = Field(default=None, sa_column=Column(JSON))

    created_at: datetime = Field(default_factory=datetime.now)
    target_goal: str | None = None
    last_optimized: datetime | None = None


# %% ../nbs/03_article.ipynb #8703aac9
def insert_article(
    session: Session,
    website_id: int,
    file_path: str,
    focus_keyword: str | None = None,
    secondary_keywords: list[str] | None = None,
    target_goal: str | None = None,
    last_optimized: datetime | None = None,
) -> Article:
    """Insert new article"""
    article = Article(
        website_id=website_id,
        file_path=file_path,
        focus_keyword=focus_keyword,
        secondary_keywords=secondary_keywords,
        target_goal=target_goal,
        last_optimized=last_optimized,
    )
    session.add(article)
    session.commit()
    session.refresh(article)
    return article


# %% ../nbs/03_article.ipynb #3f958518
def get_article_by_id(session: Session, article_id: int) -> Article | None:
    """Get article by ID"""
    return session.get(Article, article_id)


# %% ../nbs/03_article.ipynb #33635cc8
def get_article_by_path(session: Session, file_path: str) -> Article | None:
    """Get article by file path"""
    statement = select(Article).where(Article.file_path == file_path)
    return session.exec(statement).first()


# %% ../nbs/03_article.ipynb #145f3db4
def get_articles_by_website(session: Session, website_id: int) -> list[Article]:
    """Get all articles for a website"""
    statement = select(Article).where(Article.website_id == website_id)
    return session.exec(statement).all()


# %% ../nbs/03_article.ipynb #a3aa865c
def update_article_keyword(
    session: Session, article_id: int, focus_keyword: str
) -> Article | None:
    """Update article focus keyword"""
    article = session.get(Article, article_id)
    if article:
        article.focus_keyword = focus_keyword
        session.add(article)
        session.commit()
        session.refresh(article)
    return article


# %% ../nbs/03_article.ipynb #77e8a592
def delete_article(session: Session, article_id: int) -> bool:
    """Delete article"""
    article = session.get(Article, article_id)
    if article:
        session.delete(article)
        session.commit()
        return True
    return False

# %% ../nbs/03_article.ipynb #585165cd
def update_article_optimization(
    session: Session,
    article_id: int,
    target_goal: str | None = None,
    focus_keyword: str | None = None,
    secondary_keywords: list[str] | None = None,
) -> Article | None:
    """Update article optimization fields and set last_optimized to now"""
    article = session.get(Article, article_id)
    if not article:
        return None

    if target_goal:
        article.target_goal = target_goal
    if focus_keyword:
        article.focus_keyword = focus_keyword
    if secondary_keywords:
        article.secondary_keywords = secondary_keywords

    article.last_optimized = datetime.now()

    session.add(article)
    session.commit()
    session.refresh(article)

    return article

