# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_article.ipynb.

# %% auto #0
__all__ = ['Article', 'insert_article', 'get_article_by_id', 'get_article_by_path', 'get_articles_by_website',
           'update_article_keyword', 'delete_article']

# %% ../nbs/03_article.ipynb #adf11e68
from sqlmodel import SQLModel, Field, create_engine
from pydantic import field_validator
from datetime import datetime, date
from typing import Optional, Dict, Any, List
from pathlib import Path

from sqlmodel import Session, select
from typing import List, Optional

# %% ../nbs/03_article.ipynb #4fb71115
from sqlmodel import Column
from sqlalchemy import JSON

# %% ../nbs/03_article.ipynb #b08967e1
class Article(SQLModel, table=True):
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    website_id: int = Field(foreign_key="website.id")
    file_path: str  # Path to .md file
    focus_keyword: str | None = None
    secondary_keywords: List[str] | None = Field(default=None, sa_column=Column(JSON))

    created_at: datetime = Field(default_factory=datetime.now)


# %% ../nbs/03_article.ipynb #724576f0
def insert_article(
    session: Session,
    website_id: int,
    file_path: str,
    focus_keyword: str = None,
    secondary_keywords: List[str] | None = None,
) -> Article:
    """Insert new article"""
    article = Article(
        website_id=website_id,
        file_path=file_path,
        focus_keyword=focus_keyword,
        secondary_keywords=secondary_keywords,
    )
    session.add(article)
    session.commit()
    session.refresh(article)
    return article


# %% ../nbs/03_article.ipynb #b573b96b
def get_article_by_id(session: Session, article_id: int) -> Optional[Article]:
    """Get article by ID"""
    return session.get(Article, article_id)


# %% ../nbs/03_article.ipynb #eac69adc
def get_article_by_path(session: Session, file_path: str) -> Optional[Article]:
    """Get article by file path"""
    statement = select(Article).where(Article.file_path == file_path)
    return session.exec(statement).first()


# %% ../nbs/03_article.ipynb #8dafa717
def get_articles_by_website(session: Session, website_id: int) -> List[Article]:
    """Get all articles for a website"""
    statement = select(Article).where(Article.website_id == website_id)
    return session.exec(statement).all()


# %% ../nbs/03_article.ipynb #5943d10c
def update_article_keyword(
    session: Session, article_id: int, focus_keyword: str
) -> Optional[Article]:
    """Update article focus keyword"""
    article = session.get(Article, article_id)
    if article:
        article.focus_keyword = focus_keyword
        session.add(article)
        session.commit()
        session.refresh(article)
    return article


# %% ../nbs/03_article.ipynb #c95fe938
def delete_article(session: Session, article_id: int) -> bool:
    """Delete article"""
    article = session.get(Article, article_id)
    if article:
        session.delete(article)
        session.commit()
        return True
    return False
