"""A Simple API for test the basic SEO of my Websites(Astrojs,Quarto,WordPress.etc)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/old_tests.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/old_tests.ipynb 2
import glob
import pymongo
from pymongo import MongoClient
from typing import Optional
import re
import yaml
from urllib.parse import urlparse

# %% ../nbs/old_tests.ipynb 5
from typing import Optional, List
from pymongo.database import Database
from pymongo.results import InsertOneResult, UpdateResult
from bson.objectid import ObjectId
