# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_content_mapper.ipynb.

# %% auto #0
__all__ = ['SOURCE_EXTS', 'url_to_relpath', 'find_source_file', 'url_to_file_path', 'build_slug_index', 'map_all_urls_to_files']

# %% ../nbs/08_content_mapper.ipynb #f2882934
from pathlib import Path
from typing import Optional
from .index_tracking import fetch_sitemap_urls


# %% ../nbs/08_content_mapper.ipynb #841bcd4a
def url_to_relpath(url: str, base_path: str, site_url: str) -> Optional[Path]:
    try:
        url_cleaned = url.removeprefix(site_url).removesuffix(".html")
    except Exception as e:
        print(f"Error processing URL: {url} with site URL: {site_url}. Error: {e}")
        return None
    return Path(base_path) / url_cleaned


# %% ../nbs/08_content_mapper.ipynb #077f14e2
SOURCE_EXTS = (".qmd", ".md", ".ipynb",".mdx",".astro")


def find_source_file(rel_path: Path, exts=SOURCE_EXTS) -> Optional[str]:
    for ext in exts:
        candidate = rel_path.with_suffix(ext)
        if candidate.exists():
            return str(candidate)
    return None


# %% ../nbs/08_content_mapper.ipynb #32bb9b3f
def url_to_file_path(url: str, base_path: str, site_url: str) -> Optional[str]:
    """Map website URL to local file path"""
    rel_path = url_to_relpath(url, base_path, site_url)
    return find_source_file(rel_path) if rel_path else None


# %% ../nbs/08_content_mapper.ipynb #d58a88b1
def build_slug_index(base_path: str) -> dict[str, str]:
    """Build a mapping of slug → filepath by reading frontmatter from all source files"""
    import yaml
    index = {}
    for ext in SOURCE_EXTS:
        for path in Path(base_path).rglob(f"*{ext}"):
            try:
                content = path.read_text(encoding="utf-8")
                if content.startswith("---"):
                    fm = content.split("---")[1]
                    meta = yaml.safe_load(fm)
                    slug = meta.get("slug") if meta else None
                    if slug:
                        index[slug] = str(path)
            except Exception:
                continue
    return index


# %% ../nbs/08_content_mapper.ipynb #997227eb
from .gsc_storage import normalize_url

def map_all_urls_to_files(
    base_path: str, site_url: str, urls: list[str], use_slug_index: bool = False,normalize=False
) -> dict[str, str]:
    if use_slug_index:
        slug_index = build_slug_index(base_path)
        return {
            url: slug_index[slug]
            for url in urls
            if (slug := url.removeprefix(site_url).removesuffix("/")) in slug_index
        }
    return {
        normalize_url(url) if normalize else url: path
        for url in urls
        if (path := url_to_file_path(url, base_path, site_url))
    }


