# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_content_parser.ipynb.

# %% auto 0
__all__ = ['parse_metadata', 'remove_metadata', 'extract_headers', 'extract_links', 'extract_images', 'filter_internal_links',
           'filter_external_links', 'normalize_text', 'detect_phone_numbers', 'calculate_similarity', 'get_file_paths',
           'get_file_name']

# %% ../nbs/02_content_parser.ipynb 1
import re
import yaml
from pathlib import Path
from typing import Dict, List, Tuple
from urllib.parse import urlparse


# %% ../nbs/02_content_parser.ipynb 2
def parse_metadata(content: str) -> Dict:
    """Extract metadata from content frontmatter"""
    yaml_section = content.split("---")[1]
    return yaml.safe_load(yaml_section)


# %% ../nbs/02_content_parser.ipynb 3
def remove_metadata(content: str) -> str:
    """Remove frontmatter from content"""
    end = content.find('---', 3)
    return content[end + 3:].strip() if end != -1 else content


# %% ../nbs/02_content_parser.ipynb 4
def extract_headers(file_path: str) -> List[Dict]:
    """Extract all headers with metadata"""
    headings = []
    with open(file_path, "r") as file:
        for line_number, line in enumerate(file, start=1):
            line = line.strip()
            for level in range(1, 7):
                prefix = "#" * level + " "
                if line.startswith(prefix):
                    content = line.strip("#").strip()
                    headings.append({
                        "type": f"h{level}",
                        "line_number": line_number,
                        "content": content,
                        "length": len(content)
                    })
                    break
    return headings


# %% ../nbs/02_content_parser.ipynb 5
def extract_links(content: str) -> Dict[str, Dict]:
    """Extract all links with metadata"""
    links = {}
    lines = content.split('\n')
    for line_number, line in enumerate(lines, start=1):
        for match in re.finditer(r'\[(.*?)\]\((.*?)\)', line):
            title, url = match.groups()
            if url not in links:
                links[url] = {'titles': [], 'lines': []}
            links[url]['titles'].append(title)
            links[url]['lines'].append(line_number)
    return links


# %% ../nbs/02_content_parser.ipynb 6
def extract_images(content: str) -> List[Dict]:
    """Extract images with alt text"""
    matches = re.findall(r'\!\[(.*?)\]\((.*?)\)', content)
    return [{'alt_text': alt, 'url': url} for alt, url in matches]


# %% ../nbs/02_content_parser.ipynb 7
def filter_internal_links(urls: List[str], domain: str) -> List[str]:
    """Filter for internal links only"""
    return [url for url in urls 
            if urlparse(url).netloc == domain]


# %% ../nbs/02_content_parser.ipynb 8
def filter_external_links(urls: List[str], domain: str) -> List[str]:
    """Filter for external links (excluding images)"""
    image_exts = ('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.svg', '.webp')
    return [url for url in urls
            if urlparse(url).netloc != domain
            and not url.lower().endswith(image_exts)]


# %% ../nbs/02_content_parser.ipynb 9
def normalize_text(text: str) -> str:
    """Normalize text by removing extra whitespace"""
    return re.sub(r'\s+', ' ', text).strip()


# %% ../nbs/02_content_parser.ipynb 10
def detect_phone_numbers(text: str) -> List[str]:
    """Extract phone numbers from text"""
    phone_regex = re.compile(r"(\+\d{1,3})?\s*?(\d{3})\s*?(\d{3})\s*?(\d{3,4})")
    groups = phone_regex.findall(text)
    return ["".join(g) for g in groups]


# %% ../nbs/02_content_parser.ipynb 11
def calculate_similarity(text1: str, text2: str) -> float:
    """Calculate similarity ratio between two texts"""
    from difflib import SequenceMatcher
    return SequenceMatcher(None, text1, text2).ratio()


# %% ../nbs/02_content_parser.ipynb 12
def get_file_paths(pattern: str) -> List[str]:
    """Get file paths matching pattern"""
    import glob
    return glob.glob(pattern, recursive=True)


# %% ../nbs/02_content_parser.ipynb 13
def get_file_name(file_path: str) -> str:
    """Extract filename without extension from path"""
    return Path(file_path).stem

