# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_content_mapper.ipynb.

# %% auto #0
__all__ = ['url_to_file_path', 'map_all_urls_to_files']

# %% ../nbs/08_content_mapper.ipynb #f2882934
from pathlib import Path
from typing import Optional
from .index_tracking import fetch_sitemap_urls
from typing import Dict

# %% ../nbs/08_content_mapper.ipynb #32bb9b3f
def url_to_file_path(url: str, base_path: str, site_url: str) -> Optional[str]:
    """Map website URL to local file path"""
    url_cleaned = url.removeprefix(site_url).removesuffix(".html")
    file_path = base_path + url_cleaned

    for ext in [".qmd", ".md", ".ipynb"]:
        candidate = Path(file_path + ext)
        if candidate.exists():
            return str(candidate)

    return None  # No file found


# %% ../nbs/08_content_mapper.ipynb #997227eb
def map_all_urls_to_files(
    sitemap_url: str, base_path: str, site_url: str
) -> Dict[str, str]:
    """Map all sitemap URLs to their file paths"""
    urls = fetch_sitemap_urls(sitemap_url)
    mapped_urls = dict()
    mapped_urls = {
        url: path
        for url in urls
        if (path := url_to_file_path(url, base_path, site_url))
    }

    return mapped_urls

