# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_gsc_client.ipynb.

# %% auto 0
__all__ = ['GSCAuth', 'get_date_range', 'fetch_gsc_data', 'get_verified_sites']

# %% ../nbs/04_gsc_client.ipynb 1
# Required Google libraries for Search Console API access:
# Install with pip (in your terminal or notebook):


import pickle
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, Tuple, List, Dict

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request as GoogleRequest


# %% ../nbs/04_gsc_client.ipynb 2
class GSCAuth:
    """Google Search Console Authentication Handler"""

    def __init__(
        self,
        secrets_file: str = "./client_secrets.json",
        token_file: str = "./token.pickle",
    ):
        self.secrets_file = secrets_file
        self.token_file = Path(token_file)
        self.credentials = self._load_credentials()

    def _load_credentials(self) -> Optional[Credentials]:
        """Load credentials from file if they exist"""
        if self.token_file.exists():
            with open(self.token_file, "rb") as token:
                return pickle.load(token)
        return None

    def _save_credentials(self, credentials: Credentials):
        """Save credentials to file"""
        with open(self.token_file, "wb") as token:
            pickle.dump(credentials, token)

    def get_credentials(self) -> Optional[Credentials]:
        """Get current credentials, refreshing if necessary"""
        if not self.credentials:
            return None

        if self.credentials.expired:
            self.credentials.refresh(GoogleRequest())
            self._save_credentials(self.credentials)

        return self.credentials

    def authenticate(self):
        """Run OAuth flow to get credentials"""
        flow = InstalledAppFlow.from_client_secrets_file(
            self.secrets_file,
            scopes=[
                "https://www.googleapis.com/auth/webmasters.readonly",
                "https://www.googleapis.com/auth/webmasters",
            ],
        )
        self.credentials = flow.run_local_server(port=0)
        self._save_credentials(self.credentials)


# %% ../nbs/04_gsc_client.ipynb 3
def get_date_range(
    range_type: str = "today",
    days: Optional[int] = None,
    months: Optional[int] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
) -> Tuple[str, str]:
    """Generate date range for GSC queries (accounts for 3-day delay)"""
    today = datetime.now()
    latest_available = today - timedelta(days=3)

    if range_type == "today":
        date = latest_available.strftime("%Y-%m-%d")
        return date, date

    if range_type == "last_days" and days:
        end = latest_available
        start = end - timedelta(days=days)
        return start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")

    if range_type == "last_months" and months:
        end = latest_available
        start = end - timedelta(days=30 * months)
        return start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")

    if range_type == "custom" and start_date and end_date:
        start = datetime.strptime(start_date, "%Y-%m-%d")
        end = datetime.strptime(end_date, "%Y-%m-%d")
        if end.date() > latest_available.date():
            end = latest_available
        return start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")

    raise ValueError("Invalid date range parameters")


# %% ../nbs/04_gsc_client.ipynb 4
def fetch_gsc_data(
    auth: GSCAuth,
    site_url: str,
    start_date: str,
    end_date: str,
    dimensions: List[str] = None,
    row_limit: int = 25000,
) -> List[Dict]:
    """Fetch data from Google Search Console"""
    if dimensions is None:
        dimensions = ["query", "page", "country", "device"]

    service = build("searchconsole", "v1", credentials=auth.get_credentials())

    request = {
        "startDate": start_date,
        "endDate": end_date,
        "dimensions": dimensions,
        "rowLimit": row_limit,
    }

    response = service.searchanalytics().query(siteUrl=site_url, body=request).execute()

    return response.get("rows", [])


# %% ../nbs/04_gsc_client.ipynb 5
def get_verified_sites(auth: GSCAuth) -> List[Dict]:
    """Get list of verified sites"""
    service = build("searchconsole", "v1", credentials=auth.get_credentials())
    sites_list = service.sites().list().execute()

    return [
        {"site_url": site["siteUrl"], "permission_level": site["permissionLevel"]}
        for site in sites_list.get("siteEntry", [])
        if site["permissionLevel"] != "siteUnverifiedUser"
    ]

