# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_gsc_client.ipynb.

# %% auto #0
__all__ = ['GSCAuth', 'get_date_range', 'fetch_gsc_data', 'get_verified_sites']

# %% ../nbs/04_gsc_client.ipynb #752b21cc
import pickle
from datetime import datetime, timedelta
from pathlib import Path
from fastcore.basics import store_attr

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request as GoogleRequest

# %% ../nbs/04_gsc_client.ipynb #c9ecc849
class GSCAuth:
    """Google Search Console Authentication Handler"""

    def __init__(
        self,
        secrets_file: str = "./client_secrets.json",
        token_file: str = "./token.pickle",
    ):
        store_attr()
        self.token_file = Path(token_file)
        self.credentials = self._load_credentials()

    def _load_credentials(self) -> Credentials | None:
        if self.token_file.exists():
            with open(self.token_file, "rb") as token:
                return pickle.load(token)
        return None

    def _save_credentials(self, credentials: Credentials):
        with open(self.token_file, "wb") as token:
            pickle.dump(credentials, token)

    def get_credentials(self) -> Credentials | None:
        if not self.credentials:
            return None
        if self.credentials.expired:
            self.credentials.refresh(GoogleRequest())
            self._save_credentials(self.credentials)
        return self.credentials

    def authenticate(self):
        flow = InstalledAppFlow.from_client_secrets_file(
            self.secrets_file,
            scopes=[
                "https://www.googleapis.com/auth/webmasters.readonly",
                "https://www.googleapis.com/auth/webmasters",
            ],
        )
        self.credentials = flow.run_local_server(port=0)
        self._save_credentials(self.credentials)


# %% ../nbs/04_gsc_client.ipynb #b490ca7b
def get_date_range(
    range_type: str = "today",
    days: int | None = None,
    months: int | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
) -> tuple[str, str]:
    """Generate date range for GSC queries (accounts for 3-day delay)"""
    latest = datetime.now() - timedelta(days=3)

    match range_type:
        case "today":
            d = latest.strftime("%Y-%m-%d")
            return d, d
        case "last_days" if days:
            start = latest - timedelta(days=days)
            return start.strftime("%Y-%m-%d"), latest.strftime("%Y-%m-%d")
        case "last_months" if months:
            start = latest - timedelta(days=30 * months)
            return start.strftime("%Y-%m-%d"), latest.strftime("%Y-%m-%d")
        case "custom" if start_date and end_date:
            s = datetime.strptime(start_date, "%Y-%m-%d")
            e = min(datetime.strptime(end_date, "%Y-%m-%d"), latest)
            return s.strftime("%Y-%m-%d"), e.strftime("%Y-%m-%d")
        case _:
            raise ValueError("Invalid date range parameters")

# %% ../nbs/04_gsc_client.ipynb #520be733
def fetch_gsc_data(
    auth: GSCAuth,
    site_url: str,
    start_date: str,
    end_date: str,
    dimensions: list[str] | None = None,
    row_limit: int = 25000,
) -> list[dict]:
    """Fetch data from Google Search Console"""
    if dimensions is None:
        dimensions = ["query", "page", "country", "device"]

    service = build("searchconsole", "v1", credentials=auth.get_credentials())
    request = {
        "startDate": start_date,
        "endDate": end_date,
        "dimensions": dimensions,
        "rowLimit": row_limit,
    }
    return (
        service.searchanalytics()
        .query(siteUrl=site_url, body=request)
        .execute()
        .get("rows", [])
    )


# %% ../nbs/04_gsc_client.ipynb #d8e05755
def get_verified_sites(auth: GSCAuth) -> list[dict]:
    """Get list of verified sites"""
    service = build("searchconsole", "v1", credentials=auth.get_credentials())
    sites_list = service.sites().list().execute()
    return [
        {"site_url": site["siteUrl"], "permission_level": site["permissionLevel"]}
        for site in sites_list.get("siteEntry", [])
        if site["permissionLevel"] != "siteUnverifiedUser"
    ]

