# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12_gsc_insights.ipynb.

# %% auto #0
__all__ = ['INTENT_PATTERNS', 'STOP_WORDS', 'apply_strftime', 'get_date_ranges_for_comparison', 'compare_periods',
           'detect_query_trends', 'classify_intent', 'classify_page_intents', 'query_words_in_content',
           'find_missing_queries', 'find_green_keywords']

# %% ../nbs/12_gsc_insights.ipynb #8bb9bd51
from datetime import datetime, timedelta


# %% ../nbs/12_gsc_insights.ipynb #fd293b87
def apply_strftime(date: datetime):
    return date.strftime("%Y-%m-%d")


def get_date_ranges_for_comparison(days=30):
    period_a_start = datetime.now() - timedelta(days=3)
    period_a_end = period_a_start - timedelta(days=days)
    period_b_start = period_a_end
    period_b_end = period_b_start - timedelta(days=days)
    return (apply_strftime(period_a_start), apply_strftime(period_a_end)), (
        apply_strftime(period_b_start),
        apply_strftime(period_b_end),
    )


# %% ../nbs/12_gsc_insights.ipynb #4111809a
from sqlmodel import Session
from .gsc_storage import *
from .sqlite_db import *

# %% ../nbs/12_gsc_insights.ipynb #3bd595a4
def compare_periods(recent: list[dict], previous: list[dict]) -> list[dict]:
    """Compare two periods of query data and detect trends"""
    prev_by_query = {r["query"]: r for r in previous}
    trends = []
    for r in recent:
        q = r["query"]
        p = prev_by_query.get(
            q, {"total_clicks": 0, "total_impressions": 0, "avg_position": 100}
        )

        click_change = r["total_clicks"] - p["total_clicks"]
        impression_change = r["total_impressions"] - p["total_impressions"]
        position_change = p["avg_position"] - r["avg_position"]

        trends.append(
            {
                "query": q,
                "recent_clicks": r["total_clicks"],
                "prev_clicks": p["total_clicks"],
                "click_change": click_change,
                "recent_impressions": r["total_impressions"],
                "prev_impressions": p["total_impressions"],
                "impression_change": impression_change,
                "recent_position": r["avg_position"],
                "prev_position": p["avg_position"],
                "position_change": position_change,
                "trend": "rising"
                if impression_change > 0 and position_change > 0
                else "declining"
                if impression_change < 0 or position_change < 0
                else "stable",
            }
        )
    return sorted(trends, key=lambda t: t["impression_change"], reverse=True)


# %% ../nbs/12_gsc_insights.ipynb #9fb44a0b
def detect_query_trends(
    session: Session,
    site_url: str,
    page_path: str | None = None,
    days: int = 30,
    limit: int = 100,
) -> list[dict]:
    """Detect rising and declining queries, optionally filtered by page"""
    (recent_start, recent_end), (prev_start, prev_end) = get_date_ranges_for_comparison(
        days
    )
    recent = get_top_queries(
        session, site_url, recent_end, recent_start, page_path=page_path, limit=limit
    )
    previous = get_top_queries(
        session, site_url, prev_end, prev_start, page_path=page_path, limit=limit
    )

    return compare_periods(recent, previous)


# %% ../nbs/12_gsc_insights.ipynb #895c7b6d
INTENT_PATTERNS = {
    "informational": [
        "what is",
        "how to",
        "guide",
        "explain",
        "tutorial",
        "ما هو",
        "كيف",
        "شرح",
        "تعريف",
        "دليل",
    ],
    "comparison": [
        "vs",
        "alternative",
        "best",
        "compare",
        "difference",
        "مقارنة",
        "أفضل",
        "بديل",
        "الفرق بين",
        "ضد",
    ],
    "transactional": [
        "buy",
        "price",
        "review",
        "specs",
        "discount",
        "سعر",
        "شراء",
        "مراجعة",
        "مواصفات",
        "طلب",
    ],
    "commercial": [
        "pricing",
        "cheapest",
        "affordable",
        "top rated",
        "comparison",
        "worth it",
        "cost",
        "budget",
        "rental",
        "أسعار",
        "أرخص",
        "تكلفة",
        "ميزانية",
        "إيجار",
    ],
    "navigational": [
        "site:",
        "login",
        "official",
        "website",
        "github",
        "موقع",
        "تسجيل دخول",
        "الرسمي",
    ],
}


# %% ../nbs/12_gsc_insights.ipynb #3a922567
def classify_intent(query: str):
    for k, v in INTENT_PATTERNS.items():
        if any(pattern in query.lower() for pattern in v):
            return k
    return "informational"

# %% ../nbs/12_gsc_insights.ipynb #0d16babd
from .gsc_storage import select, GSCAnalytics, func, partial, compose


def classify_page_intents(
    session: Session,
    site_url: str,
    start_date: str,
    end_date: str,
    country: str | None = None,
    page_path: str | None = None,
    limit: int = 10,
) -> list[dict]:
    """Get top performing queries, optionally filtered by page"""
    base_query = select(
        GSCAnalytics.query,
        func.sum(GSCAnalytics.clicks).label("total_clicks"),
        func.sum(GSCAnalytics.impressions).label("total_impressions"),
        func.avg(GSCAnalytics.position).label("avg_position"),
        func.avg(GSCAnalytics.ctr).label("avg_ctr"),
    )
    filters = [
        partial(filter_site, site_url=site_url),
        partial(filter_dates, start=start_date, end=end_date),
    ]
    if country:
        filters.append(partial(filter_dimension, dimension="country", value=country))
    if page_path:
        filters.append(lambda q: q.where(GSCAnalytics.page.contains(page_path)))

    query = (
        compose(*filters)(base_query)
        .where(GSCAnalytics.query.isnot(None))
        .group_by(GSCAnalytics.query)
        .order_by(func.sum(GSCAnalytics.clicks).desc())
        .limit(limit)
    )

    return [
        {**row._asdict(), "intent": classify_intent(row.query)}
        for row in session.exec(query)
    ]


# %% ../nbs/12_gsc_insights.ipynb #af887a1b
STOP_WORDS = {
    "a",
    "an",
    "the",
    "is",
    "it",
    "in",
    "to",
    "for",
    "of",
    "and",
    "or",
    "how",
    "what",
    "who",
    "which",
    "this",
    "that",
    "هل",
    "في",
    "من",
    "على",
    "هو",
    "هذا",
    "ما",
}


def query_words_in_content(query: str, content: str) -> bool:
    """Check if all significant words from a query appear in the content"""
    content_lower = content.lower()
    words = [w for w in query.lower().split() if w not in STOP_WORDS and len(w) > 1]
    return all(word in content_lower for word in words)


# %% ../nbs/12_gsc_insights.ipynb #e4a26439
def find_missing_queries(queries: list[dict], content: str) -> list[dict]:
    """Find GSC queries that don't appear in the page content"""
    # return [q for q in queries if q["query"].lower() not in content_lower]
    return [q for q in queries if not query_words_in_content(q['query'],content)]


# %% ../nbs/12_gsc_insights.ipynb #d722220c
def find_green_keywords(
    session: Session,
    site_url: str,
    page_path: str,
    content: str,
    days: int = 30,
    limit: int = 100,
) -> list[dict]:
    """Find emerging keywords not yet in content"""
    trends = detect_query_trends(session, site_url, page_path=page_path, days=days, limit=limit)
    rising = [t for t in trends if t["trend"] == "rising" and t["prev_impressions"] <= 5]
    return find_missing_queries(rising, content)

