# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_models.ipynb.

# %% auto #0
__all__ = ['get_all_websites', 'delete_website']

# %% ../nbs/01_models.ipynb #8af54b8e
from sqlmodel import Field, SQLModel, UniqueConstraint
from datetime import datetime
from .sqlite_db import SQLiteDB
import re
from pydantic import field_validator
from pathlib import Path

# %% ../nbs/01_models.ipynb #193c2559
class Website(SQLModel, table=True):
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    url: str = Field(unique=True)
    name: str
    desc: str | None = None
    lang: str = "en"
    created_at: datetime = Field(default_factory=datetime.now)

    @field_validator("url")
    @classmethod
    def validate_url(cls, v: str) -> str:
        from urllip.parse import urlparse

        parsed = urlparse(v)
        if not all([parsed.scheme, parsed.netloc]):
            raise ValueError(f"Invalid URL: {v}")
        return v

    @field_validator("name")
    @classmethod
    def validate_name(cls, v: str) -> str:
        if not v or len(v.strip()) < 1:
            raise ValueError(f"Invalid Name: {v}")
        return v

    @field_validator("lang")
    @classmethod
    def validate_lang(cls, v: str) -> str:
        if not re.match(r"^[a-z]{2}(-[A-Z]{2})?$", v):
            raise ValueError(f"Invalid Language Code: {v}")
        return v

# %% ../nbs/01_models.ipynb #c4038cd8
def get_all_websites(session):
    """Get all websites from database"""
    from sqlmodel import select

    return session.exec(select(Website)).all()


# %% ../nbs/01_models.ipynb #1be5e48c
def delete_website(session, website_id: int):
    from sqlmodel import delete

    session.exec(delete(Website).where(Website.id == website_id))
    session.commit()


# %% ../nbs/01_models.ipynb #d4c8eab3
class GSCAnalytics(SQLModel, table=True):
    __table_args__ = (
        UniqueConstraint("site_url", "date", "query", "page", "country", "device"),
        {"extend_existing": True},
    )
    id: int | None = Field(default=None, primary_key=True)
    site_url: str
    date: str
    query: str | None = None
    page: str | None = None
    country: str | None = None
    device: str | None = None
    clicks: int = 0
    impressions: int = 0
    ctr: float = 0.0
    position: float = 0.0
    created_at: datetime = Field(default_factory=datetime.now)


# %% ../nbs/01_models.ipynb #1fd437e0
class IndexStatus(SQLModel, table=True):
    __table_args__ = {"extend_existing": True}
    id: int | None = Field(default=None, primary_key=True)
    site_url: str
    page_url: str 
    verdict: str
    coverage_state: str | None = None
    last_crawl_time: str | None = None
    indexing_state: str | None = None
    robots_txt_state: str | None = None
    checked_at: datetime = Field(default_factory=datetime.now)

