# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_schema_extractor.ipynb.

# %% auto #0
__all__ = ['path', 'website_name', 'start', 'end', 'extract_faq_queries']

# %% ../nbs/14_schema_extractor.ipynb #e9e9dc9b
from sqlmodel import Session, select
from .article import get_article_by_path, insert_article, Article
from .sqlite_db import SQLiteDB
from .models import Website
from .content_mapper import map_all_urls_to_files,fetch_sitemap_urls

# %% ../nbs/14_schema_extractor.ipynb #9fa5f0bb
from .gsc_storage import get_top_queries
from .article import  get_articles_by_website
from .gsc_client import get_date_range

# %% ../nbs/14_schema_extractor.ipynb #8bbd92a1
import re

_ARABIC_RE = re.compile(r"[\u0600-\u06FF]")

_EN_Q_WORDS = re.compile(
    r"^(what|who|why|when|where|which|how|can|is|are|do|does|did|will|should|"
    r"could|would|may|might|shall)\b",
    re.IGNORECASE,
)

# Require a space after ما/من/هل etc. to avoid matching nouns like ماكينة/مادة/مانع
_AR_Q_WORDS = re.compile(
    r"^("
    r"ما (هو|هي|هم|هي|الح|ال|يع|تع|يج|ه[ا-ي])|"  # ما هو / ما هي / ما ال...
    r"ماذا |"
    r"من أين |من اين |"
    r"أين |اين |"
    r"كيف |كيفية |كيفيه |"
    r"هل |"
    r"لماذا |"
    r"كم |"
    r"بماذا |"
    r"لمن |"
    r"متى |"
    r"أي |"
    r"من "
    r")"
)

def _is_arabic(text: str) -> bool:
    return len(_ARABIC_RE.findall(text)) > len(text) * 0.3

def _is_question(query: str) -> bool:
    q = query.strip()
    if q.endswith("?") or q.endswith("؟"):
        return True
    return bool(_AR_Q_WORDS.match(q) if _is_arabic(q) else _EN_Q_WORDS.match(q))

def extract_faq_queries(rows: list[dict] | list[str]) -> list[str]:
    """Filter GSC queries that are questions (Arabic or English).
    Accepts either raw query strings or dicts from get_top_queries."""
    queries = (r["query"] if isinstance(r, dict) else r for r in rows)
    return list(filter(_is_question, queries))


# %% ../nbs/14_schema_extractor.ipynb #028dbefd
#| eval: false
path = "https://shelid.com/"
website_name="https://shelid.com/"

start, end = get_date_range("last_days", days=90*8)
print(start, end)

with db.get_session() as session:
    articles = get_articles_by_website(session, website_id=2)
    for article in articles: 
        page_path= article.url.removeprefix(website_name)
        top_query = get_top_queries(session=session,site_url="sc-domain:shelid.com",start_date=start,end_date=end,page_path=page_path,limit=1000,sort_by="impressions")
        if  extract_faq_queries(top_query)==[]:
            continue
        print(extract_faq_queries(top_query))
        print(article.file_path)

