# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_seo_content_analysis.ipynb.

# %% auto #0
__all__ = ['calculate_keyword_density', 'check_h1_count', 'keyword_in_first_section', 'check_paragraph_length',
           'keyword_in_metadata', 'keyword_in_alt_texts', 'analyze_header_distribution']

# %% ../nbs/10_seo_content_analysis.ipynb #bce0ad5a
from .content_parser import extract_headers, remove_metadata

# %% ../nbs/10_seo_content_analysis.ipynb #9b955c78
def calculate_keyword_density(content: str, keyword: str) -> dict:
    """Calculate keyword density and positions"""
    content_lower = content.lower()
    keyword_lower = keyword.lower()

    positions = []
    pos = 0
    while (pos := content_lower.find(keyword_lower, pos)) != -1:
        positions.append(pos)
        pos += 1

    total_words = len(content.split())
    count = len(positions)
    density = (count / total_words * 100) if total_words > 0 else 0

    return {
        "keyword": keyword,
        "count": count,
        "density": density,
        "positions": positions,
    }

# %% ../nbs/10_seo_content_analysis.ipynb #41378f3c
def check_h1_count(
    headers: list[dict], title: str | None = None, is_quarto: bool = False
) -> dict:
    """Check H1 count — for Quarto, the title frontmatter field acts as H1"""
    h1s = [h for h in headers if h["type"] == "h1"]

    if is_quarto and title:
        return {"h1_count": 1, "has_single_h1": True, "h1_source": "title"}

    return {"h1_count": len(h1s), "has_single_h1": len(h1s) == 1}

# %% ../nbs/10_seo_content_analysis.ipynb #c1209cfb
def keyword_in_first_section(content: str, keyword: str, percent: int = 10) -> bool:
    """Check if keyword appears in first X% of content"""
    section_length = int(len(content) * percent / 100)
    return keyword.lower() in content[:section_length].lower()

# %% ../nbs/10_seo_content_analysis.ipynb #8d3eded2
def check_paragraph_length(content: str) -> dict:
    """Check average paragraph length"""
    paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
    sentences_per_para = [len(p.split(". ")) for p in paragraphs]
    avg = sum(sentences_per_para) / len(sentences_per_para) if paragraphs else 0

    return {
        "avg_sentences_per_paragraph": avg,
        "is_optimal": 2 <= avg <= 4,
    }

# %% ../nbs/10_seo_content_analysis.ipynb #445edd7d
def keyword_in_metadata(metadata: dict, keyword: str) -> dict:
    """Check if keyword is in title, excerpt, description"""
    kw = keyword.lower()
    return {
        "in_title": kw in str(metadata.get("title", "")).lower(),
        "in_excerpt": kw in str(metadata.get("excerpt", "")).lower(),
        "in_description": kw in str(metadata.get("description", "")).lower(),
    }

# %% ../nbs/10_seo_content_analysis.ipynb #24b7c979
def keyword_in_alt_texts(images: list[dict], keyword: str) -> bool:
    """Check if keyword appears in any image alt text"""
    return any(keyword.lower() in img.get("alt_text", "").lower() for img in images)

# %% ../nbs/10_seo_content_analysis.ipynb #a0d712ef
def analyze_header_distribution(headers: list[dict]) -> dict:
    """Analyze header hierarchy distribution"""
    distribution: dict[str, int] = {}
    for h in headers:
        h_type = h["type"]
        distribution[h_type] = distribution.get(h_type, 0) + 1

    total = len(headers)
    percentages = {
        k: (v / total * 100) if total > 0 else 0 for k, v in distribution.items()
    }

    return {"counts": distribution, "percentages": percentages}
