# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_seo_content_analysis.ipynb.

# %% auto #0
__all__ = ['db', 'calculate_keyword_density', 'find_cannibalized', 'check_h1_count', 'keyword_in_first_section',
           'check_paragraph_length', 'keyword_in_metadata', 'keyword_in_alt_texts', 'analyze_header_distribution',
           'check_keyword_placement', 'content_freshness']

# %% ../nbs/10_seo_content_analysis.ipynb #9b955c78
def calculate_keyword_density(content: str, keyword: str) -> dict:
    """Calculate keyword density using word-level matching"""
    content_lower = content.lower()
    keyword_lower = keyword.lower()

    content_words = content_lower.split()
    keyword_words = keyword_lower.split()
    n = len(keyword_words)

    positions = []
    for i in range(len(content_words) - n + 1):
        if content_words[i:i + n] == keyword_words:
            positions.append(i)

    total_words = len(content_words)
    count = len(positions)
    density = (count / total_words * 100) if total_words > 0 else 0

    return {
        "keyword": keyword,
        "count": count,
        "density": density,
        "positions": positions,
    }


# %% ../nbs/10_seo_content_analysis.ipynb #a9a04575619ac96c
from .article import get_articles_by_website
from .content_parser import get_page_content
from .sqlite_db import SQLiteDB
from .models import  GSCAnalytics
from .gsc_insights import  get_top_queries
from .gsc_client import get_date_range
from sqlmodel import  select
db = SQLiteDB()


# %% ../nbs/10_seo_content_analysis.ipynb #8157f3d628982cbe
def find_cannibalized(session, website_id, site_url, start, end):
    articles = get_articles_by_website(session=session, website_id=website_id)

    # 1. Exact focus_keyword matches
    keyword_to_articles = {}
    for article in articles:
        kw = article.focus_keyword
        if kw:
            keyword_to_articles.setdefault(kw, []).append(article.url)

    exact_matches = [
        {"keyword": kw, "pages": urls}
        for kw, urls in keyword_to_articles.items()
        if len(urls) >= 2
    ]

    # 2. GSC-based: 2+ pages ranking for same top query
    gsc_matches = []
    all_queries = [r["query"] for r in get_top_queries(session, site_url, start, end, limit=1000)]


    for query in all_queries:
        pages = session.exec(
            select(GSCAnalytics.page).where(
                GSCAnalytics.site_url == site_url,
                GSCAnalytics.query == query,
                GSCAnalytics.date.between(start, end),
                GSCAnalytics.position <= 20,
            ).distinct()
        ).all()
        if len(pages) >= 2:
            gsc_matches.append({"query": query, "pages": pages})

    return {"exact_matches": exact_matches, "gsc_matches": gsc_matches}



# %% ../nbs/10_seo_content_analysis.ipynb #41378f3c
def check_h1_count(
        headers: list[dict], title: str | None = None, title_is_h1: bool = False
) -> dict:
    """Check H1 count — for Quarto, the title frontmatter field acts as H1"""
    h1s = [h for h in headers if h["type"] == "h1"]

    if title_is_h1 and title:
        return {"h1_count": 1, "has_single_h1": True, "h1_source": "title"}

    return {"h1_count": len(h1s), "has_single_h1": len(h1s) == 1}

# %% ../nbs/10_seo_content_analysis.ipynb #c1209cfb
def keyword_in_first_section(content: str, keyword: str, percent: int = 10) -> bool:
    """Check if keyword appears in first X% of content"""
    section_length = int(len(content) * percent / 100)
    return keyword.lower() in content[:section_length].lower()

# %% ../nbs/10_seo_content_analysis.ipynb #8d3eded2
def check_paragraph_length(content: str) -> dict:
    """Check average paragraph length"""
    paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
    sentences_per_para = [len(p.split(". ")) for p in paragraphs]
    avg = sum(sentences_per_para) / len(sentences_per_para) if paragraphs else 0

    return {
        "avg_sentences_per_paragraph": avg,
        "is_optimal": 2 <= avg <= 4,
    }

# %% ../nbs/10_seo_content_analysis.ipynb #445edd7d
def keyword_in_metadata(metadata: dict, keyword: str, desc_field: str = "description") -> dict:
    """Check if keyword is in title, excerpt, description"""
    kw = keyword.lower()
    return {
        "in_title": kw in str(metadata.get("title", "")).lower(),
        "in_description": kw in str(metadata.get(desc_field, "")).lower(),
    }

# %% ../nbs/10_seo_content_analysis.ipynb #24b7c979
def keyword_in_alt_texts(images: list[dict], keyword: str) -> bool:
    """Check if keyword appears in any image alt text"""
    return any(keyword.lower() in img.get("alt_text", "").lower() for img in images)

# %% ../nbs/10_seo_content_analysis.ipynb #a0d712ef
def analyze_header_distribution(headers: list[dict]) -> dict:
    """Analyze header hierarchy distribution"""
    distribution: dict[str, int] = {}
    for h in headers:
        h_type = h["type"]
        distribution[h_type] = distribution.get(h_type, 0) + 1

    total = len(headers)
    percentages = {
        k: (v / total * 100) if total > 0 else 0 for k, v in distribution.items()
    }

    return {"counts": distribution, "percentages": percentages}

# %% ../nbs/10_seo_content_analysis.ipynb #81cdf15b
def check_keyword_placement(keyword, metadata, headers, content, url, desc_field="description", title_is_h1=False):
    if not keyword:
        return {
            "in_h1": False,
            "in_url": False,
            "keyword_in_meta": {
                "in_title": False,
                "in_description": False,
            },
            "keyword_at_first": False,
        }

    h1_from_headers = any(
        keyword.lower() in h["content"].lower() for h in headers if h["type"] == "h1"
    )
    if title_is_h1:
        title = str(metadata.get("title", ""))
        in_h1 = h1_from_headers or keyword.lower() in title.lower()
    else:
        in_h1 = h1_from_headers

    in_url = keyword.lower() in url.lower()
    keyword_in_meta = keyword_in_metadata(metadata, keyword, desc_field=desc_field)
    keyword_at_first = keyword_in_first_section(content, keyword)
    return {
        "in_h1": in_h1,
        "in_url": in_url,
        "keyword_in_meta": keyword_in_meta,
        "keyword_at_first": keyword_at_first,
    }


# %% ../nbs/10_seo_content_analysis.ipynb #f1c9ac58
def content_freshness(last_updated: str, days=180) -> dict:
    """check content freshness based on the last updated date last 180 days is considered fresh"""
    from datetime import datetime, timedelta

    try:
        if isinstance(last_updated, str):
            last_updated_date = datetime.strptime(last_updated, "%Y-%m-%d")
        else:
            last_updated_date = datetime(
                last_updated.year, last_updated.month, last_updated.day
            )

        now = datetime.now()
        delta = now - last_updated_date

        return {
            "last_updated": last_updated,
            "days_since_update": delta.days,
            "is_fresh": delta.days <= days,
        }
    except ValueError:
        return {
            "last_updated": last_updated,
            "error": "Invalid date format. Use YYYY-MM-DD.",
        }
