# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_seo_report.ipynb.

# %% auto #0
__all__ = ['website_name', 'start', 'end', 'sync_articles_to_db', 'find_duplicate_metadata', 'analyze_links',
           'check_heading_structure', 'analyze_article', 'generate_seo_report', 'print_issues_report']

# %% ../nbs/09_seo_report.ipynb #55e2ad2b
from sqlmodel import Session, select
from .article import get_article_by_path, insert_article, Article
from .sqlite_db import SQLiteDB
from .models import Website
from .content_mapper import map_all_urls_to_files, fetch_sitemap_urls
from seo_rat.content_parser import (
    parse_metadata,
    parse_notebook_metadata,
    remove_metadata,
    extract_headers,
    extract_images,
    extract_links,
    filter_external_links,
    filter_internal_links,
    check_desc_length,
    check_content_length,
    check_title_length,
    imgs_missing_alts,
    extract_notebook_content,
)
from .seo_content_analysis import check_h1_count, check_keyword_placement


# %% ../nbs/09_seo_report.ipynb #fb2feeae
def sync_articles_to_db(
        session: Session, website_id: int, url_file_mapping: dict[str, str]
):
    """Insert all articles into database"""
    for url, file_path in url_file_mapping.items():
        # print(f"Inserting {url} -> {file_path}")
        if file_path:  # Only if file exists
            existing = session.exec(
                select(Article).where(
                    Article.file_path == file_path,
                    Article.website_id == website_id
                )
            ).first()
            if not existing:
                insert_article(session, website_id, file_path, url=url)


# %% ../nbs/09_seo_report.ipynb #24bd6d69
def find_duplicate_metadata(
        session: Session, field: str, website_id: int, similarity_threshold: float = 0.9,
) -> list[dict]:
    """Find pages with duplicate or very similar metadata fields"""
    from seo_rat.content_parser import parse_metadata, calculate_similarity

    articles = session.exec(select(Article).where(Article.website_id == website_id)).all()
    values = {}

    # Collect all field values
    for article in articles:
        with open(article.file_path, "r") as f:
            if article.file_path.endswith(".ipynb"):
                metadata = parse_notebook_metadata(f.read())
                values[article.file_path] = metadata.get(field, "")
            elif article.file_path.endswith(".md") or article.file_path.endswith(
                    ".qmd"
            ):
                metadata = parse_metadata(f.read())
                values[article.file_path] = metadata.get(field, "")

    # Find duplicates
    duplicates = []
    checked = set()

    for path1, field1 in values.items():
        for path2, field2 in values.items():
            if path1 >= path2 or (path1, path2) in checked:
                continue
            if not field1 or not field2:
                continue

            similarity = calculate_similarity(field1, field2)
            if similarity >= similarity_threshold:
                duplicates.append(
                    {
                        "file1": path1,
                        "file2": path2,
                        f"{field}_1": field1,
                        f"{field}_2": field2,
                        "similarity": similarity,
                    }
                )
            checked.add((path1, path2))

    return duplicates


# %% ../nbs/09_seo_report.ipynb #06c02666
from .gsc_storage import get_top_queries
from .article import get_articles_by_website
from .gsc_client import get_date_range
from .seo_content_analysis import check_keyword_placement, content_freshness
from .gsc_insights import find_missing_queries

# %% ../nbs/09_seo_report.ipynb #f1e511d0
website_name = "https://emdadelgaz.com/"

start, end = get_date_range("last_days", days=90 * 8)
print(start, end)

with db.get_session() as session:
    articles = get_articles_by_website(session, website_id=3)
    for article in articles:
        page_path = article.url.removeprefix(website_name)
        print(page_path)
        print(article)
        break
        top_query = get_top_queries(session=session, site_url="sc-domain:emdadelgaz.com", start_date=start,
                                    end_date=end, page_path=page_path, limit=1, sort_by="impressions")
        top_5_query = get_top_queries(session=session, site_url="sc-domain:emdadelgaz.com", start_date=start,
                                      end_date=end, page_path=page_path, limit=5, sort_by="impressions")
        try:
            print(top_query[0]['query'])
            article.focus_keyword = top_query[0]['query']
            article.secondary_keywords = [q["query"] for q in top_5_query[:5]]
            session.add(article)
            session.commit()
        except IndexError:
            print("No queries found for this page")


# %% ../nbs/09_seo_report.ipynb #69064449
def analyze_links(content: str, domain: str) -> dict:
    """Analyze internal and external links in content"""
    links = extract_links(content)
    all_urls = list(links.keys())

    internal = filter_internal_links(all_urls, domain)
    external = filter_external_links(all_urls, domain)

    return {
        "total_links": len(all_urls),
        "internal_count": len(internal),
        "external_count": len(external),
        "internal_links": internal,
        "external_links": external,
    }


# %% ../nbs/09_seo_report.ipynb #a3d9bbce
def check_heading_structure(headers):
    ans = {}
    has_h2 = any(h["type"] == "h2" for h in headers)
    ans["has_h2"] = has_h2
    levels = [int(h["type"][1]) for h in headers]
    ans["skipped_levels"] = []

    for l in range(len(levels) - 1):
        if levels[l + 1] - levels[l] > 1:
            ans["skipped_levels"].append({"from": headers[l], "to": headers[l + 1]})

    return ans


# %% ../nbs/09_seo_report.ipynb #24b0b9a4
def analyze_article(
        article: Article,
        domain: str,
        is_quarto: bool,
        title_is_h1: bool = False,
        desc_field: str = "description",
        title_field: str = "title",
        date_field: str = "date"
) -> dict:
    """Run all SEO checks for a single article and return its report dict"""
    with open(article.file_path, "r") as f:
        raw_content = f.read()

    if article.file_path.endswith(".ipynb"):
        metadata = parse_notebook_metadata(raw_content)
        content = extract_notebook_content(raw_content, is_quarto=is_quarto)
    else:
        metadata = parse_metadata(raw_content)
        content = remove_metadata(raw_content)

    headers = extract_headers(article.file_path)
    images = extract_images(content)

    return {
        "file_path": article.file_path,
        "title_check": check_title_length(metadata.get(title_field, "")),
        "description_check": check_desc_length(metadata.get(desc_field, "")),
        "content_check": check_content_length(content),
        "h1_check": check_h1_count(
            headers, title=metadata.get("title", ""), title_is_h1=title_is_h1
        ),
        "missing_alts": imgs_missing_alts(images),
        "link_analysis": analyze_links(content, domain),
        "keyword_placement": check_keyword_placement(
            article.focus_keyword,
            metadata=metadata,
            headers=headers,
            content=content,
            url=article.url,
            desc_field=desc_field,
            title_is_h1=title_is_h1,
        ),
        "content_freshness": content_freshness(metadata.get(date_field, "")),
        "content_structure": check_heading_structure(headers),
    }


# %% ../nbs/09_seo_report.ipynb #a1e0e1e8
def generate_seo_report(
        session: Session,
        website_id: int,
        domain: str,
        is_quarto: bool,
        title_is_h1: bool = False,
        desc_field: str = "description",
        title_field: str = "title",
        date_field: str = "date",
) -> dict:
    """Generate comprehensive SEO report for all pages"""

    articles = session.exec(
        select(Article).where(Article.website_id == website_id)
    ).all()

    page_reports = []
    issues = {}
    start, end = get_date_range("last_days", days=90 * 8)

    for article in articles:
        try:
            report = analyze_article(
                article,
                domain,
                is_quarto,
                title_is_h1=title_is_h1,
                desc_field=desc_field,
                title_field=title_field,
                date_field=date_field,
            )

            queries = get_top_queries(
                session=session,
                site_url=f"sc-domain:{domain}",
                start_date=start,
                end_date=end,
                page_path=article.url.removeprefix(f"https://{domain}/"),
                limit=500,
                sort_by="impressions",
            )
            content = remove_metadata(open(article.file_path, "r").read())
            missing_queries = find_missing_queries(queries=queries, content=content)

            page_issues = []

            if not report["h1_check"]["has_single_h1"]:
                page_issues.append("Multiple or no H1")
            if not report["content_check"]["is_sufficient"]:
                page_issues.append("Content too short")
            if report["link_analysis"]["internal_count"] == 0:
                page_issues.append("No internal links, at least 3 recommended")
            if report["link_analysis"]["external_count"] == 0:
                page_issues.append("No external links")
            if report["missing_alts"]:
                page_issues.append(f"Images missing alt text ({len(report['missing_alts'])})")
            if report["content_structure"]["skipped_levels"]:
                for skip in report["content_structure"]["skipped_levels"]:
                    page_issues.append(
                        f"Skipped heading: {skip['from']['type']} → {skip['to']['type']} (line {skip['to']['line_number']})"
                    )
            if not report["content_structure"]["has_h2"]:
                page_issues.append("No H2 headings, at least one recommended")

            tc = report["title_check"]
            if tc["status"] != "optimal":
                page_issues.append(f"Title {tc['status']} ({tc['length']} chars, range {tc['min']}-{tc['max']})")

            dc = report["description_check"]
            if dc["status"] != "optimal":
                page_issues.append(f"Description {dc['status']} ({dc['length']} chars, range {dc['min']}-{dc['max']})")

            if not report["content_freshness"]["is_fresh"]:
                page_issues.append(f"Stale content ({report['content_freshness']['days_since_update']} days old)")

            if article.focus_keyword:
                if not report["keyword_placement"]["in_h1"]:
                    page_issues.append("Focus keyword not in H1")
                if not report["keyword_placement"]["keyword_in_meta"]["in_description"]:
                    page_issues.append("Focus keyword not in description")
                if not report["keyword_placement"]["keyword_in_meta"]["in_title"]:
                    page_issues.append("Focus keyword not in title")
                if not report["keyword_placement"]["keyword_at_first"]:
                    page_issues.append("Focus keyword not in first 100 words")

            if page_issues or missing_queries:
                issues[article.url or article.file_path] = {
                    "file_path": article.file_path,
                    "issues": page_issues,
                    "data": {
                        "missing_queries": missing_queries,
                        "keyword_placement": report.get("keyword_placement", {}),
                    }
                }

            page_reports.append(report)

        except Exception as e:
            print(f"Error analyzing {article.file_path}: {e}")

    duplicate_titles = find_duplicate_metadata(
        session, "title", website_id=website_id, similarity_threshold=0.9
    )
    duplicate_descriptions = find_duplicate_metadata(
        session, "description", website_id=website_id, similarity_threshold=0.9
    )

    total_issues = sum(len(v["issues"]) for v in issues.values())

    return {
        "total_pages": len(articles),
        "pages_analyzed": len(page_reports),
        "page_reports": page_reports,
        "duplicate_titles": duplicate_titles,
        "duplicate_descriptions": duplicate_descriptions,
        "issues": issues,
        "summary": {
            "total_issues": total_issues,
            "pages_with_issues": len(issues),
            "duplicate_titles_count": len(duplicate_titles),
            "duplicate_descriptions_count": len(duplicate_descriptions),
        },
    }


# %% ../nbs/09_seo_report.ipynb #487b7796
def print_issues_report(report: dict) -> None:
    """Print SEO issues sorted from most issues to fewest."""
    issues = report["issues"]
    summary = report["summary"]

    print(f"Pages analysed : {report['pages_analyzed']} / {report['total_pages']}")
    print(f"Pages with issues: {summary['pages_with_issues']}")
    print(f"Total issue count: {summary['total_issues']}")
    print(f"Duplicate titles : {summary['duplicate_titles_count']}")
    print(f"Duplicate descs  : {summary['duplicate_descriptions_count']}")
    print("=" * 70)

    sorted_issues = sorted(issues.items(), key=lambda x: len(x[1]["issues"]), reverse=True)

    for url, data in sorted_issues:
        count = len(data["issues"])
        print(f"\n[{count} issue{'s' if count != 1 else ''}] {url}")
        for i, issue in enumerate(data["issues"], 1):
            print(f"  {i}. {issue}")

        missing = data.get("data", {}).get("missing_queries", [])
        if missing:
            print(f" Missing queries ({len(missing)}):")
            for q in missing:
                print(
                    f"      - {q['query']} (clicks: {q['total_clicks']}, impressions: {q['total_impressions']}, pos: {q['avg_position']:.1f})")



