"""A Simple API for configure the DB connection with Sqlite"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_sqlite.ipynb.

# %% auto #0
__all__ = ['get_session']

# %% ../nbs/00_sqlite.ipynb #96fa0d1b
from sqlmodel import create_engine, Session, SQLModel
from pathlib import Path
from sqlalchemy.exc import DatabaseError
from datetime import datetime
import os
from dotenv import load_dotenv

load_dotenv()


# %% ../nbs/00_sqlite.ipynb #ed723feac521dba
def get_session(db_url: str | None = None) -> Session:
    "Create a SQLite database session. Uses `SEO_RAT_DB_URL` env var if `db_url` is not provided."
    if db_url is None:
        db_url = os.getenv("SEO_RAT_DB_URL")
    engine = create_engine(db_url)
    SQLModel.metadata.create_all(engine)
    return Session(engine)
