"""A Simple API for configure the DB connection with Sqlite"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_sqlite.ipynb.

# %% auto #0
__all__ = ['SQLiteDB']

# %% ../nbs/00_sqlite.ipynb #9baf8a2f
from sqlmodel import create_engine, Session, SQLModel
from pathlib import Path

# %% ../nbs/00_sqlite.ipynb #6b61df25
class SQLiteDB:

    def __init__(self, db_path: str = "./data/seo.db"):
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        self.engine = create_engine(f"sqlite:///{db_path}")
        SQLModel.metadata.create_all(self.engine)

    def get_session(self):
        return Session(self.engine)
